sass:
  sass_dir: assets/css
plugins:
  - jekyll-seo-tag
  - jekyll-feed
title: Baby Hacker
description: Something Awesome Project
collections:
  tags:
    output: true
    permalink: tags/:path/
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge